export function workbenchHtml(fallback:string){return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Diego · Estúdio de carrosséis</title><link rel="stylesheet" href="/design/workbench.css"></head>
<body><div id="studio" hidden>
<header class="toolbar"><a class="brand" href="/">d<span>m</span><i></i></a><div class="project-heading"><span class="eyebrow">ESTÚDIO DE CARROSSÉIS</span><h1 id="title" hidden>Carrossel</h1><select id="project-select" aria-label="Projeto"></select></div><span id="status" class="status">Carregando</span><div class="top-actions"><button id="new-project">Novo</button><button id="refresh">Atualizar</button><button id="new-version">Criar versão</button><button id="export" class="primary">Exportar PNGs ↗</button></div></header>
<div id="notice" role="status" aria-live="polite" hidden></div><div id="pending" hidden><span id="pending-text"></span><button type="button" id="pending-open">Ver proposta</button></div>
<div class="workspace"><aside class="slides-panel"><div class="panel-heading"><h2>Slides <span id="count"></span></h2><button id="grid-toggle" aria-pressed="false">Grade</button></div><nav id="slides" aria-label="Slides"></nav><div class="copy-badge">✓ Copy preservada<span>Ajustes visuais mantêm teu texto.</span></div></aside>
<main class="canvas-panel"><div class="canvas-toolbar"><div class="version-control"><label for="version">VERSÃO</label><select id="version"><option value="">Principal</option></select><button id="promote" hidden>Usar como principal</button></div><div class="view-controls"><div class="view-modes" role="group" aria-label="Visualização"><button type="button" data-view="slide" aria-pressed="true">Slide</button><button type="button" data-view="instagram" aria-pressed="false">Instagram</button></div><label class="safe-toggle"><input type="checkbox" id="safe-area"> Área segura</label></div></div><div id="stage"><div id="frame"><img id="canvas" alt="Slide selecionado"><div id="live" hidden><iframe id="live-frame" title="Prévia ao vivo" tabindex="-1"></iframe><span class="live-badge">Prévia aproximada · salva para o render real</span></div><div id="safe-overlay" hidden aria-hidden="true"><i class="safe-box"></i><i class="footer-zone"></i></div></div><span id="missing" hidden>Atualiza o render para ver este slide.</span><div id="instagram" hidden><article class="ig-post"><header><span class="ig-avatar"></span><strong class="ig-handle"></strong><span class="ig-more">•••</span></header><div class="ig-media"><img id="ig-image" alt=""><button type="button" class="ig-prev" aria-label="Anterior">‹</button><button type="button" class="ig-next" aria-label="Próximo">›</button><span class="ig-count"></span></div><div class="ig-dots"></div><div class="ig-actions" aria-hidden="true">♡ &nbsp; ◯ &nbsp; ➤<span>⌑</span></div><p class="ig-caption"><strong class="ig-handle"></strong> <span id="ig-caption-text"></span></p></article><aside class="ig-grid"><span class="eyebrow">NA GRADE DO PERFIL (3:4)</span><div class="ig-grid-tile"><img id="ig-grid-image" alt="Capa recortada como na grade do perfil"></div><p class="muted">O Instagram recorta a capa em 3:4 na grade: o título precisa sobreviver ao corte.</p></aside></div></div><div id="grid" hidden></div><div class="canvas-footer"><button id="previous" aria-label="Slide anterior">←</button><span id="slide-label"></span><button id="next" aria-label="Próximo slide">→</button></div></main>
<aside class="inspector"><div class="inspector-title"><span class="eyebrow">DIREÇÃO VISUAL</span><h2 id="inspector-title">Slide 01</h2></div><form id="adjust-form">
<label>Família do carrossel<select name="family"><option value="editorial_clean">Editorial · Inter</option><option value="cinematic_condensed">Cinemática · Anton</option></select></label>
<label>Composição<select name="composition"><option value="full_bleed">Capa com imagem</option><option value="cinematic_fade">Imagem com degradê</option><option value="image_card">Imagem em card</option><option value="text_only">Texto</option><option value="giant_statement">Afirmação</option><option value="minimal_pause">Pausa</option><option value="quote">Citação</option><option value="contrast">Contraste</option></select></label>
<div class="pair"><label>Alinhamento<select name="align"><option value="left">Esquerda</option><option value="center">Centro</option></select></label><label>Posição<select name="position"><option value="top">Acima</option><option value="center">Centro</option><option value="bottom">Abaixo</option></select></label></div>
<details open><summary>Tipografia</summary><label>Headline <output data-for="headline_size_delta"></output><input name="headline_size_delta" type="range" min="-24" max="24" step="1"></label><label>Corpo <output data-for="body_size_delta"></output><input name="body_size_delta" type="range" min="-4" max="8" step="1"></label><label>Espaço entre blocos <output data-for="block_gap"></output><input name="block_gap" type="range" min="24" max="72" step="1"></label><label>Ajuste do título<select name="fit"><option value="preferred">Usar tamanho escolhido</option><option value="fill">Preencher espaço (capa e afirmação)</option></select></label></details>
<details open><summary>Imagem</summary><label>Imagem do slide<select name="asset_id"><option value="">Sem imagem</option></select></label><button type="button" id="upload-button" class="upload">＋ Adicionar imagem</button><input type="file" id="upload-file" accept="image/png,image/jpeg,image/webp" hidden><label>Foco horizontal <output data-for="focal_x"></output><input name="focal_x" type="range" min="0" max="100"></label><label>Foco vertical <output data-for="focal_y"></output><input name="focal_y" type="range" min="0" max="100"></label><label>Zoom <output data-for="image_scale"></output><input name="image_scale" type="range" min="1" max="1.5" step="0.01"></label></details>
<div id="fit-summary" class="fit-summary"></div><button id="save" class="primary save" type="submit">Salvar e atualizar slide</button><p class="muted">A imagem é atualizada após salvar. A fonte nunca fica abaixo do mínimo legível.</p></form><details class="copy-section"><summary>Texto do slide</summary><h3 id="copy-headline"></h3><p id="copy-body"></p></details></aside></div>
</div><div id="fallback"><h1>Preview do carrossel</h1><p id="offline-note">Abrindo o estúdio…</p><main>${fallback}</main></div>
<dialog id="variant-dialog"><form id="variant-form"><span class="eyebrow">EXPERIMENTA OUTRO VISUAL</span><h2>Criar uma versão</h2><p>A copy é compartilhada. O visual principal fica preservado.</p><label>Nome<input name="name" placeholder="capa-cinematica" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="60"></label><label>Família<select name="family"><option value="cinematic_condensed">Cinemática · Anton</option><option value="editorial_clean">Editorial · Inter</option></select></label><div class="dialog-actions"><button type="button" data-close>Cancelar</button><button class="primary" type="submit">Criar versão</button></div></form></dialog>
<dialog id="export-dialog"><form id="export-form"><span class="eyebrow">ÚLTIMA CONFERÊNCIA</span><h2>Teu carrossel, pronto para baixar</h2><p>O arquivo ZIP contém os PNGs numerados na ordem dos slides.</p><label>Quem revisou<input name="reviewer" required minlength="2" maxlength="80" autocomplete="name" placeholder="Teu nome"></label><label class="check"><input type="checkbox" name="confirmed" required>Conferi todos os slides, a leitura e as imagens.</label><label>Nota da revisão<textarea name="note" required minlength="5" placeholder="O que tu conferiu nesta versão?"></textarea></label><div class="dialog-actions"><button type="button" data-close>Voltar</button><button class="primary" type="submit">Aprovar e baixar ZIP</button></div></form></dialog>
<dialog id="upload-dialog"><form id="upload-form"><span class="eyebrow">BIBLIOTECA DO PROJETO</span><h2>Adicionar imagem</h2><p id="upload-name"></p><label>Origem e direitos de uso<textarea name="rights" required placeholder="Ex.: foto minha, fornecida para este carrossel"></textarea></label><div class="dialog-actions"><button type="button" data-close>Cancelar</button><button class="primary" type="submit">Usar neste slide</button></div></form></dialog>
<dialog id="approve-dialog"><form id="approve-form"><span class="eyebrow">COPY PRONTA</span><h2 id="approve-title">Proposta</h2><pre id="approve-text"></pre><label>Quem aprova<input name="by" required minlength="2" maxlength="80" autocomplete="name" placeholder="Teu nome"></label><label class="check"><input type="checkbox" name="confirmed" required>Li a proposta e aprovo estas mudanças na copy.</label><div class="dialog-actions"><button type="button" data-close>Agora não</button><button class="primary" type="submit">Aprovar e aplicar</button></div></form></dialog><dialog id="create-dialog"><form id="create-form"><span class="eyebrow">DA COPY AO CARROSSEL</span><h2>Novo carrossel</h2><p>Cola 8–12 painéis. Usa P1, P2… em linhas separadas, ou separa os painéis por uma linha em branco. A primeira linha de cada painel é o título.</p><label>Nome do projeto<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="60" placeholder="meu-proximo-post"></label><label>Copy pronta<textarea name="copy" required class="copy-input" placeholder="P1&#10;Título da capa&#10;&#10;P2&#10;Título do segundo slide&#10;Texto do slide..."></textarea></label><label>Família<select name="family"><option value="editorial_clean">Editorial · Inter</option><option value="cinematic_condensed">Cinemática · Anton</option></select></label><div class="dialog-actions"><button type="button" data-close>Cancelar</button><button type="submit" class="primary">Criar e renderizar</button></div></form></dialog>
<script src="/design/workbench.js"></script></body></html>`;}
